[package]
name = "actor"
version = "0.1.0"
authors = ["eastack <admin@eastack.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1", features = ["full"]}
anyhow = "1"