/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.programing.in.action;

import me.eastack.Observable;
import me.eastack.Subscriber;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Observable.create((Observable.OnSubscribe<? extends Integer>) subscriber -> {
            for (int i = 0; i < 10; i++) {
                subscriber.onNext(i);
            }
        }).subscribe(new Subscriber<Integer>() {
            @Override
            public void onCompleted() {
                System.out.println("Completed");
            }

            @Override
            public void onError(Throwable t) {
                System.out.println("Exception!!");
            }

            @Override
            public void onNext(Integer var) {
                System.out.println(var);
            }
        });
    }
}
